
CREATE PROCEDURE [dbo].[sp_UBER_EATS_REMOVE_DATA_FROM_STAGING]
WITH EXECUTE AS 'dbo'
AS

BEGIN
	 			 
				TRUNCATE TABLE [dbo].[STAGING_UBER_EATS_DEFAULT];
				TRUNCATE TABLE [dbo].[STAGING_UBER_EATS_FRANCE_BELGIUM];
				TRUNCATE TABLE [dbo].[STAGING_UBER_EATS_EUROPE_MIDDLE_EAST_AFRICA];
END
 
	 
GO